name = "Alphabird"
license = "MIT"
licenselink = "https://github.com/supernetnavi/alphabird/blob/master/LICENSE"
description = "Simple theme"
homepage = "https://github.com/supernetnavi/alphabird"
tags = ["blog"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "supernetnavi"
